// The most-asked conceptual interview questions with concise, level-appropriate
// answers. Complements the coding exercises with the "explain it" knowledge
// interviewers probe. Each question is tagged Junior / Mid / Senior and grouped by
// category. Pure reference data; rendered as searchable, filterable flashcards.
export type Level = 'Junior' | 'Mid' | 'Senior'

export interface QA {
  q: string
  a: string
  category: string
  level: Level
  code?: string
}

export const QUESTIONS: QA[] = [
  // ---------------- C# Fundamentals ----------------
  { category: 'C# Fundamentals', level: 'Junior', q: 'Value types vs reference types?',
    a: 'Value types (int, bool, struct, enum) hold their data directly and are copied on assignment — two variables are independent. Reference types (class, string, array, delegate) hold a reference to a heap object — copies point at the same object. Value types usually live on the stack, reference types on the heap.' },
  { category: 'C# Fundamentals', level: 'Mid', q: 'What is boxing and unboxing? Why care?',
    a: 'Boxing wraps a value type in a heap object (object o = 5); unboxing extracts it back. Both allocate/copy and cost performance, so avoid them on hot paths — generics (List<int>) exist largely to prevent boxing.',
    code: 'object o = 42;   // boxing\nint n = (int)o;  // unboxing' },
  { category: 'C# Fundamentals', level: 'Junior', q: 'ref vs out vs in parameters?',
    a: '`ref` passes by reference and must be initialized by the caller (two-way). `out` also passes by reference but the METHOD must assign it (to return extra values). `in` passes by read-only reference (an optimization for large structs).' },
  { category: 'C# Fundamentals', level: 'Junior', q: 'const vs readonly?',
    a: '`const` is a compile-time constant baked into callers — must be a literal, implicitly static. `readonly` is set at runtime (declaration or constructor) and can differ per instance. Use readonly when the value is known only at construction.' },
  { category: 'C# Fundamentals', level: 'Junior', q: 'Why is string immutable, and when use StringBuilder?',
    a: 'Every change to a string creates a new string (the old is garbage) — safe to share but wasteful in loops. For many concatenations use StringBuilder, which edits a mutable buffer in place.' },
  { category: 'C# Fundamentals', level: 'Mid', q: '== vs .Equals()?',
    a: 'For value types both compare values. For reference types, == compares references by default (unless overloaded, like string), while .Equals() can be overridden for value equality. Records and string override both to compare by value.' },
  { category: 'C# Fundamentals', level: 'Junior', q: 'is vs as?',
    a: '`is` tests a type (and can pattern-match: `if (o is int n)`). `as` attempts a cast and returns null on failure instead of throwing — only for reference/nullable types.' },
  { category: 'C# Fundamentals', level: 'Mid', q: 'var vs dynamic?',
    a: '`var` is still static typing — the compiler infers the exact type at compile time. `dynamic` defers all type checking to runtime, losing safety and IntelliSense. Prefer var; use dynamic only for interop/COM/loosely-typed data.' },
  { category: 'C# Fundamentals', level: 'Mid', q: 'Managed vs unmanaged code?',
    a: 'Managed code runs under the CLR, which handles memory (GC), type safety, and exceptions. Unmanaged code (native C/C++, OS handles, sockets) runs outside it — you must release those resources yourself, typically via IDisposable.' },
  { category: 'C# Fundamentals', level: 'Mid', q: 'class vs struct — when use a struct?',
    a: 'class = reference type (heap, shared); struct = value type (copied). Use a struct for small, short-lived, immutable data (a Point, Money) to avoid heap allocations. Default to class otherwise — big structs are expensive to copy.' },

  // ---------------- OOP ----------------
  { category: 'OOP', level: 'Junior', q: 'The four pillars of OOP?',
    a: 'Encapsulation (hide data behind a clean API), Inheritance (reuse via is-a), Polymorphism (one interface, many implementations), and Abstraction (expose what, hide how).' },
  { category: 'OOP', level: 'Junior', q: 'Abstract class vs interface?',
    a: 'An interface is a pure contract (C# 8+ allows default methods) and a type can implement many. An abstract class can hold state and shared implementation but you inherit only one. Interface = capability ("can fly"); abstract class = shared base ("is an Animal").' },
  { category: 'OOP', level: 'Junior', q: 'Method overloading vs overriding?',
    a: 'Overloading = same name, different parameters, resolved at compile time (compile-time polymorphism). Overriding = a subclass replaces a virtual/abstract base method, resolved at runtime (runtime polymorphism).' },
  { category: 'OOP', level: 'Mid', q: 'virtual / override / new — the difference?',
    a: '`virtual` marks a method that can be overridden; `override` replaces it, and calls through a base reference run the override. `new` HIDES the base method instead — the version called depends on the reference type, not the object. Hiding is usually a code smell.' },
  { category: 'OOP', level: 'Mid', q: 'What does sealed do?',
    a: 'On a class it prevents inheritance; on an override it stops further overriding. Used for safety, intent, and a small perf win (the JIT can devirtualize calls).' },
  { category: 'OOP', level: 'Mid', q: 'Composition vs inheritance?',
    a: 'Inheritance is is-a; composition is has-a (an object holds other objects). Prefer composition — more flexible, avoids fragile deep hierarchies, and underpins dependency injection ("favor composition over inheritance").' },
  { category: 'OOP', level: 'Junior', q: 'Name the C# access modifiers.',
    a: 'public (everyone), private (same class), protected (class + subclasses), internal (same assembly), protected internal (assembly OR subclasses), private protected (subclasses within the same assembly).' },

  // ---------------- Memory & GC ----------------
  { category: 'Memory & GC', level: 'Mid', q: 'How does the .NET garbage collector work?',
    a: 'It\'s a generational mark-and-sweep collector. New objects start in Gen 0; survivors get promoted to Gen 1 then Gen 2. Gen 0 collects often and cheaply; Gen 2 (and the Large Object Heap) rarely. It marks live objects from roots, reclaims the rest, and compacts.' },
  { category: 'Memory & GC', level: 'Mid', q: 'Explain the Dispose pattern / IDisposable.',
    a: 'IDisposable.Dispose() deterministically releases unmanaged resources (files, sockets, handles). Wrap usage in `using` so Dispose runs even on exceptions. The full pattern adds a finalizer as a safety net and calls GC.SuppressFinalize(this) in Dispose.' },
  { category: 'Memory & GC', level: 'Mid', q: 'Finalizer vs Dispose?',
    a: 'Dispose is deterministic — you (or `using`) call it exactly when done. A finalizer (~ClassName) runs non-deterministically at GC time and delays reclamation. Prefer Dispose; use a finalizer only as a backstop for unmanaged resources.' },
  { category: 'Memory & GC', level: 'Senior', q: 'What commonly causes memory leaks in .NET?',
    a: 'The GC handles most memory, but you can still leak by keeping objects reachable: unremoved event handlers (publisher keeps subscriber alive), static collections that grow forever, undisposed unmanaged resources, and caches without eviction.' },
  { category: 'Memory & GC', level: 'Mid', q: 'Stack vs heap?',
    a: 'The stack is fast, per-thread storage for locals and call frames, freed when a method returns. The heap stores reference-type objects, managed by the GC. Value types can live on the heap too (boxed, or as fields of a class).' },

  // ---------------- Collections ----------------
  { category: 'Collections', level: 'Junior', q: 'Array vs List vs LinkedList?',
    a: 'Array is fixed-size, contiguous, fastest indexing. List<T> is a resizable array — great default, O(1) index, amortized O(1) add. LinkedList<T> has O(1) insert/remove at a known node but O(n) indexing and poor cache locality — rarely worth it.' },
  { category: 'Collections', level: 'Junior', q: 'Dictionary vs Hashtable?',
    a: 'Dictionary<K,V> is generic (type-safe, no boxing) and the modern choice. Hashtable is the old non-generic version (object keys, boxing). For concurrency use ConcurrentDictionary, not either.' },
  { category: 'Collections', level: 'Mid', q: 'IEnumerable vs ICollection vs IList?',
    a: 'IEnumerable<T> = iterate forward-only. ICollection<T> adds Count, Add, Remove. IList<T> adds index access and Insert. Accept the least specific one your method needs (usually IEnumerable<T>).' },
  { category: 'Collections', level: 'Junior', q: 'When would you use a HashSet?',
    a: 'When you need fast membership tests and uniqueness (O(1) Contains/Add) and don\'t care about order or key→value mapping — e.g. "have I seen this?" or de-duplicating.' },

  // ---------------- LINQ ----------------
  { category: 'LINQ', level: 'Mid', q: 'Deferred vs immediate execution?',
    a: 'Most operators (Where, Select) are deferred — the query runs only when enumerated (foreach, ToList, Count). ToList/ToArray/Count/First execute immediately. Deferred means the query re-runs each iteration and reflects later data changes.' },
  { category: 'LINQ', level: 'Mid', q: 'IEnumerable vs IQueryable? (very common)',
    a: 'IEnumerable<T> runs in memory (LINQ to Objects) — the whole collection is pulled and filtered locally. IQueryable<T> builds an expression tree a provider (EF Core) translates to SQL and runs on the DB. Using IEnumerable on a DbSet accidentally pulls the whole table into memory — a classic bug.' },
  { category: 'LINQ', level: 'Mid', q: 'First vs FirstOrDefault vs Single?',
    a: 'First throws if empty; FirstOrDefault returns default if empty. Single expects EXACTLY one (throws on zero or many); SingleOrDefault allows zero. Use Single when "more than one" is a real bug you want surfaced.' },
  { category: 'LINQ', level: 'Junior', q: 'Select vs SelectMany?',
    a: 'Select maps each item to one result (a list of lists if each maps to a collection). SelectMany flattens — it maps each item to a collection and concatenates them into one sequence.' },

  // ---------------- Async & Concurrency ----------------
  { category: 'Async & Concurrency', level: 'Mid', q: 'What actually happens when you await a Task?',
    a: 'The method returns to its caller at the await point (it doesn\'t block a thread). The compiler builds a state machine; when the task completes, execution resumes (by default on the captured context). So async frees the thread during I/O waits.' },
  { category: 'Async & Concurrency', level: 'Junior', q: 'Task vs Thread?',
    a: 'A Thread is a low-level OS thread you manage. A Task is a higher-level promise of future work, usually on the thread pool, composable with await. Prefer Task/async; raw threads are for rare dedicated long-running work.' },
  { category: 'Async & Concurrency', level: 'Mid', q: 'Why is async void dangerous?',
    a: 'You can\'t await it (the caller can\'t know when it finished or if it failed), and its exceptions escape try/catch and can crash the process. Return async Task instead — the only valid async void is a UI event handler.' },
  { category: 'Async & Concurrency', level: 'Senior', q: 'How does blocking on async cause a deadlock?',
    a: 'Calling .Result or .Wait() blocks the current thread. If the awaited continuation needs that same thread (a captured SynchronizationContext in classic ASP.NET/UI), they wait on each other forever. Fix: async all the way down — never block on async.' },
  { category: 'Async & Concurrency', level: 'Senior', q: 'What does ConfigureAwait(false) do?',
    a: 'It tells await not to resume on the captured context — resume on any thread pool thread instead. Use it in library code to avoid deadlocks and reduce overhead. In app code you often want the context, so leave it off.' },
  { category: 'Async & Concurrency', level: 'Senior', q: 'Task vs ValueTask?',
    a: 'Task is a heap object allocated per call. ValueTask avoids that allocation when the result is often already available synchronously (a cache hit). Use ValueTask only on hot paths; never await it twice or store it.' },
  { category: 'Async & Concurrency', level: 'Mid', q: 'What is a race condition, and how do you prevent it?',
    a: 'When two threads touch shared state and the result depends on timing (two threads doing count++ can lose an update). Prevent with `lock` (mutual exclusion), Interlocked (atomic ops), or immutable/thread-safe types.' },
  { category: 'Async & Concurrency', level: 'Senior', q: 'What are async streams (IAsyncEnumerable)?',
    a: 'A sequence produced and consumed asynchronously — `await foreach` over an IAsyncEnumerable<T> built with `async` + `yield return`. Great for streaming large or paged data without loading it all at once.' },

  // ---------------- Exceptions ----------------
  { category: 'Exceptions', level: 'Mid', q: 'throw vs throw ex — does it matter?',
    a: 'Yes. `throw;` re-throws preserving the original stack trace. `throw ex;` resets it to the current line, hiding where the error came from. Prefer plain `throw;` in catch blocks.' },
  { category: 'Exceptions', level: 'Mid', q: 'What is an exception filter?',
    a: 'A `when` condition on a catch — the handler runs only if it\'s true, without unwinding the stack otherwise. E.g. `catch (HttpRequestException e) when (e.StatusCode == 429)`.' },
  { category: 'Exceptions', level: 'Senior', q: 'When should you throw vs return an error?',
    a: 'Throw for truly exceptional, unexpected situations (invalid state, bugs). For expected failures (validation, "not found"), prefer a result/Try-pattern — exceptions are expensive and shouldn\'t drive normal control flow.' },

  // ---------------- .NET Runtime ----------------
  { category: '.NET Runtime', level: 'Mid', q: 'What are the CLR, IL, and JIT?',
    a: 'C# compiles to IL (Intermediate Language) in an assembly. At runtime the CLR (Common Language Runtime) manages execution, and the JIT compiles IL to native code on demand. The CLR also provides GC, type safety, and exceptions.' },
  { category: '.NET Runtime', level: 'Junior', q: '.NET Framework vs .NET Core vs .NET 5+?',
    a: '.NET Framework is the old Windows-only runtime (legacy). .NET Core was the cross-platform rewrite. From .NET 5 they unified into just ".NET" (5–9…) — cross-platform, faster, the path forward for all new work.' },
  { category: '.NET Runtime', level: 'Mid', q: 'What is an assembly?',
    a: 'The unit of deployment and versioning — a .dll/.exe with compiled IL, metadata, and a manifest. Assemblies define type/visibility boundaries (that\'s what `internal` is scoped to).' },
  { category: '.NET Runtime', level: 'Senior', q: 'What is reflection, and its downside?',
    a: 'Inspecting/invoking types at runtime (Type, MethodInfo, Activator). It powers DI, serializers, and ORMs, but it\'s slow and breaks compile-time safety — avoid on hot paths; cache or use source generators.' },

  // ---------------- Delegates, Events, Generics ----------------
  { category: 'Delegates & Generics', level: 'Mid', q: 'delegate vs event?',
    a: 'A delegate is a type that holds method references (a function pointer). An event is a restricted wrapper: outsiders can only subscribe (+=) and unsubscribe (-=), not invoke or overwrite it. Events are the safe way to expose notifications.' },
  { category: 'Delegates & Generics', level: 'Junior', q: 'Func vs Action vs Predicate?',
    a: 'Built-in delegate types. Action takes args, returns void. Func takes args and returns a value (last type param is the return). Predicate<T> takes a T, returns bool (a Func<T,bool>).' },
  { category: 'Delegates & Generics', level: 'Senior', q: 'What is a closure?',
    a: 'A lambda that "captures" variables from its enclosing scope, keeping them alive after the method returns. Watch the classic loop-variable capture gotcha and unintended object lifetime extension.' },
  { category: 'Delegates & Generics', level: 'Mid', q: 'Why generics? What are constraints?',
    a: 'Type-safe, reusable code without boxing (List<int> vs ArrayList). Constraints (`where T : …`) restrict the type so you can use its members — `where T : IComparable<T>` enables CompareTo; `where T : class, new()` allows `new T()`.' },
  { category: 'Delegates & Generics', level: 'Senior', q: 'Covariance vs contravariance?',
    a: 'Covariance (`out`) lets you use a more-derived type — IEnumerable<Dog> as IEnumerable<Animal>. Contravariance (`in`) lets you use a less-derived type — Action<Animal> as Action<Dog>. They keep generics flexible yet type-safe.' },

  // ---------------- ASP.NET Core ----------------
  { category: 'ASP.NET Core', level: 'Mid', q: 'What is middleware?',
    a: 'Components forming the request pipeline; each can inspect/modify the request, call the next, and act on the response coming back (an "onion"). Order matters — e.g. authentication before authorization, exception handling first.' },
  { category: 'ASP.NET Core', level: 'Mid', q: 'Explain the DI service lifetimes.',
    a: 'Transient = new instance every request for it. Scoped = one per HTTP request. Singleton = one for the app lifetime. Classic bug: injecting a Scoped/Transient service into a Singleton "captures" it and it outlives its scope.' },
  { category: 'ASP.NET Core', level: 'Mid', q: 'What is Kestrel?',
    a: 'The cross-platform, high-performance web server built into ASP.NET Core. In production it often sits behind a reverse proxy (IIS, Nginx, YARP) for TLS termination and load balancing.' },
  { category: 'ASP.NET Core', level: 'Senior', q: 'How do you secure an API (authn/authz)?',
    a: 'Authentication proves who you are (JWT bearer tokens or OAuth2/OIDC); authorization decides what you can do (roles/policies via [Authorize]). Use HTTPS, validate tokens, and prefer policy-based authorization beyond simple roles.' },

  // ---------------- EF Core & Data ----------------
  { category: 'EF Core & Data', level: 'Mid', q: 'What is the N+1 query problem?',
    a: 'Loading a list (1 query) then lazily loading a related item per row (N more queries) = N+1 round trips. Fix by loading related data in one query with Include/projection or a join.' },
  { category: 'EF Core & Data', level: 'Mid', q: 'Change tracking and AsNoTracking?',
    a: 'EF tracks loaded entities so SaveChanges knows what changed — useful for updates but adds overhead. For read-only queries use AsNoTracking() to skip it: less memory, faster.' },
  { category: 'EF Core & Data', level: 'Senior', q: 'Lazy vs eager vs explicit loading?',
    a: 'Eager: load related data up front with Include (one query). Lazy: load automatically on first access (can cause N+1). Explicit: load on demand via .Load(). Prefer eager/projection to control round trips.' },
  { category: 'EF Core & Data', level: 'Senior', q: 'Is the Repository pattern needed over EF Core?',
    a: 'Debated. DbContext already IS a repository + unit of work, so wrapping it can add ceremony for little benefit. A repository can help testability and hide EF from the domain, but many teams query DbSet directly. Know both sides.' },

  // ---------------- SQL ----------------
  { category: 'SQL', level: 'Junior', q: 'Primary key vs foreign key?',
    a: 'A primary key uniquely identifies each row in a table (unique, not null). A foreign key is a column that references another table\'s primary key, enforcing a relationship (referential integrity).' },
  { category: 'SQL', level: 'Junior', q: 'INNER JOIN vs LEFT JOIN?',
    a: 'INNER JOIN returns only rows with a match in both tables. LEFT JOIN returns all rows from the left table plus matches from the right (NULLs where none match). RIGHT/FULL are the mirror/both.' },
  { category: 'SQL', level: 'Junior', q: 'WHERE vs HAVING?',
    a: 'WHERE filters individual rows before grouping. HAVING filters groups after GROUP BY (and can use aggregate functions like COUNT). WHERE can\'t use aggregates.' },
  { category: 'SQL', level: 'Junior', q: 'DELETE vs TRUNCATE vs DROP?',
    a: 'DELETE removes rows (optionally with WHERE), logged, can roll back. TRUNCATE removes ALL rows fast, minimal logging, resets identity. DROP removes the whole table/structure.' },
  { category: 'SQL', level: 'Mid', q: 'Clustered vs non-clustered index?',
    a: 'A clustered index defines the physical row order — one per table (often the primary key). Non-clustered indexes are separate structures pointing back to rows — you can have many. Indexes speed reads but slow writes and use space.' },
  { category: 'SQL', level: 'Mid', q: 'What is a transaction? What is ACID?',
    a: 'A transaction is a unit of work that fully succeeds or fully rolls back. ACID = Atomicity (all-or-nothing), Consistency (valid state), Isolation (concurrent transactions don\'t corrupt each other), Durability (committed data survives crashes).' },
  { category: 'SQL', level: 'Mid', q: 'What is database normalization?',
    a: 'Organizing tables to reduce redundancy and anomalies. 1NF: atomic columns; 2NF: no partial dependency on part of a composite key; 3NF: no dependency on non-key columns. Denormalize deliberately for read performance.' },
  { category: 'SQL', level: 'Mid', q: 'UNION vs UNION ALL?',
    a: 'Both combine result sets with the same columns. UNION removes duplicates (extra sort/dedupe cost); UNION ALL keeps all rows and is faster. Use UNION ALL unless you truly need de-duplication.' },
  { category: 'SQL', level: 'Mid', q: 'What are window functions?',
    a: 'Functions like ROW_NUMBER(), RANK(), SUM() OVER (PARTITION BY … ORDER BY …) that compute across a set of rows related to the current row WITHOUT collapsing them like GROUP BY. Great for running totals, rankings, and "top N per group".' },
  { category: 'SQL', level: 'Senior', q: 'Explain transaction isolation levels.',
    a: 'They trade consistency for concurrency: Read Uncommitted (dirty reads), Read Committed (default; no dirty reads), Repeatable Read (no non-repeatable reads), Serializable (no phantoms, most locking). Higher isolation = more correctness but more blocking.' },
  { category: 'SQL', level: 'Senior', q: 'How do you find and fix a slow query?',
    a: 'Read the execution plan for table scans, missing indexes, and bad estimates. Common fixes: add/covering indexes, avoid SELECT *, make predicates sargable (no functions on indexed columns), reduce round trips, and update statistics.' },
  { category: 'SQL', level: 'Senior', q: 'Optimistic vs pessimistic concurrency?',
    a: 'Pessimistic locks rows so others wait (safe, but contention). Optimistic assumes no conflict and checks a version/rowversion at save time, retrying on conflict (better for low-contention, high-read systems — EF Core uses a concurrency token).' },
  { category: 'SQL', level: 'Senior', q: 'When would you denormalize?',
    a: 'When read performance matters more than write simplicity — e.g. reporting/analytics, caching computed values, or avoiding expensive joins at scale. You trade some redundancy and update complexity for faster reads.' },

  // ---------------- Cloud & DevOps ----------------
  { category: 'Cloud & DevOps', level: 'Junior', q: 'What is CI/CD?',
    a: 'Continuous Integration = automatically build and test every change so problems surface early. Continuous Delivery/Deployment = automatically release those changes to staging/production. It shortens feedback loops and reduces risky manual steps.' },
  { category: 'Cloud & DevOps', level: 'Junior', q: 'What is a container (Docker)?',
    a: 'A lightweight, isolated package of your app plus its dependencies that runs the same everywhere. Unlike a VM, containers share the host OS kernel — so they\'re smaller and start in seconds. Built from an image via a Dockerfile.' },
  { category: 'Cloud & DevOps', level: 'Junior', q: 'Container vs virtual machine?',
    a: 'A VM virtualizes hardware and runs a full guest OS (heavy, minutes to boot). A container virtualizes the OS and shares the host kernel (lightweight, seconds to boot). Containers give density and portability; VMs give stronger isolation.' },
  { category: 'Cloud & DevOps', level: 'Junior', q: 'What is Infrastructure as Code (IaC)?',
    a: 'Defining servers, networks, and services in version-controlled files (Terraform, Bicep, ARM) instead of clicking in a portal. Benefits: repeatable, reviewable, and reproducible environments.' },
  { category: 'Cloud & DevOps', level: 'Mid', q: 'Docker image vs container?',
    a: 'An image is the immutable blueprint (layers of filesystem + config). A container is a running instance of an image. One image → many containers, like a class and its objects.' },
  { category: 'Cloud & DevOps', level: 'Mid', q: 'What is Kubernetes and why use it?',
    a: 'A container orchestrator: it schedules containers across machines, restarts failed ones, scales them, does rolling updates, service discovery, and load balancing. Use it when you run many containers and need self-healing and scaling.' },
  { category: 'Cloud & DevOps', level: 'Mid', q: 'Blue-green vs canary deployment?',
    a: 'Blue-green keeps two environments and switches all traffic from old (blue) to new (green) at once — instant rollback. Canary releases the new version to a small % of users first, watching metrics before ramping up. Both aim for zero-downtime, low-risk releases.' },
  { category: 'Cloud & DevOps', level: 'Mid', q: 'Horizontal vs vertical scaling?',
    a: 'Vertical = a bigger machine (more CPU/RAM) — simple but capped and a single point of failure. Horizontal = more machines behind a load balancer — near-limitless and resilient, but needs stateless services. Cloud favors horizontal.' },
  { category: 'Cloud & DevOps', level: 'Mid', q: 'Readiness vs liveness health checks?',
    a: 'Liveness = "is the app alive?" — if it fails, the orchestrator restarts the pod. Readiness = "is it ready to serve traffic?" — if it fails, traffic is withheld until it recovers (e.g. warming up or a dependency is down).' },
  { category: 'Cloud & DevOps', level: 'Mid', q: 'Why use a message queue?',
    a: 'To decouple services and absorb load spikes: a producer drops work on a queue (RabbitMQ, Azure Service Bus, Kafka) and consumers process it at their own pace. Adds resilience and scalability, at the cost of eventual consistency.' },
  { category: 'Cloud & DevOps', level: 'Mid', q: 'How do you manage secrets and config?',
    a: 'Never commit secrets. Use environment variables and a secrets manager (Azure Key Vault, AWS Secrets Manager, Kubernetes Secrets). Rotate them, scope access least-privilege, and inject at runtime — .NET reads them via IConfiguration.' },
  { category: 'Cloud & DevOps', level: 'Senior', q: 'What is observability (logs, metrics, traces)?',
    a: 'The three pillars: logs (discrete events), metrics (numeric time series like latency/error rate), and distributed traces (a request\'s path across services). Together they let you diagnose issues in production — .NET supports OpenTelemetry.' },
  { category: 'Cloud & DevOps', level: 'Senior', q: 'What is the Twelve-Factor App?',
    a: 'A set of principles for cloud-native apps: config in the environment, stateless processes, treat backing services as attached resources, build/release/run separation, disposability, dev/prod parity, logs as streams. It makes apps portable and scalable.' },
  { category: 'Cloud & DevOps', level: 'Senior', q: 'How do you achieve zero-downtime deployments?',
    a: 'Rolling/blue-green/canary releases, health checks so traffic only hits ready instances, backward-compatible database migrations (expand-then-contract), graceful shutdown draining in-flight requests, and feature flags to decouple deploy from release.' },
  { category: 'Cloud & DevOps', level: 'Senior', q: 'Serverless / Functions — when and why?',
    a: 'Serverless (Azure Functions, AWS Lambda) runs your code on demand with no servers to manage and pay-per-use scaling to zero. Great for event-driven, spiky, or glue workloads. Watch cold starts, execution limits, and statelessness.' },
  { category: 'Cloud & DevOps', level: 'Senior', q: 'RTO vs RPO in disaster recovery?',
    a: 'RTO (Recovery Time Objective) = how fast you must be back up. RPO (Recovery Point Objective) = how much data loss is acceptable (drives backup/replication frequency). They shape your backup, replication, and multi-region strategy.' },

  // ---------------- AI & LLM ----------------
  { category: 'AI & LLM', level: 'Junior', q: 'What is a token and a context window?',
    a: 'A token is the unit an LLM reads/writes — roughly ¾ of a word (~4 chars). The context window is the max tokens a model can consider at once (prompt + response). You must keep total tokens under that limit.' },
  { category: 'AI & LLM', level: 'Junior', q: 'What is an embedding?',
    a: 'A vector of numbers representing text\'s meaning, so similar meanings sit close together. You compare them with cosine similarity — the basis of semantic search and RAG.' },
  { category: 'AI & LLM', level: 'Mid', q: 'What is RAG (Retrieval-Augmented Generation)?',
    a: 'Instead of relying on the model\'s memory, you retrieve relevant chunks from your own data (via embeddings + a vector DB) and put them in the prompt. It grounds answers in your data and reduces hallucinations, without retraining.' },
  { category: 'AI & LLM', level: 'Mid', q: 'What does temperature do?',
    a: 'It controls sampling randomness. Low temperature = focused, near-deterministic output (good for extraction/classification); high = more creative and varied (good for brainstorming). Often paired with top-p/top-k.' },
  { category: 'AI & LLM', level: 'Mid', q: 'How do you keep a long chat within the context window?',
    a: 'Budget tokens: keep the system prompt + most recent messages, and summarize or drop older turns. For long-term memory, store and retrieve past context via embeddings (RAG) instead of stuffing it all in.' },
  { category: 'AI & LLM', level: 'Senior', q: 'What is prompt injection and how do you defend against it?',
    a: 'Malicious text (in user input or retrieved documents) that hijacks the model\'s instructions. Defenses: treat external content as untrusted, separate instructions from data, validate/structure outputs, least-privilege tool access, and never let model output directly trigger dangerous actions.' },
  { category: 'AI & LLM', level: 'Senior', q: 'How do you evaluate an LLM feature?',
    a: 'Build an eval set of representative inputs with expected qualities; score with exact/rule checks, embeddings similarity, or an LLM-as-judge with a rubric. Track metrics across prompt/model changes so you know improvements are real — not vibes.' },
  { category: 'AI & LLM', level: 'Mid', q: 'What is function/tool calling?',
    a: 'The model returns a structured request (name + JSON args) to call one of your functions — e.g. lookupOrder(id). Your code runs it and feeds the result back. It\'s how LLMs take real actions and stay grounded; agents chain multiple such calls.' },

  // ---------------- Microservices ----------------
  { category: 'Microservices', level: 'Junior', q: 'Monolith vs microservices — trade-offs?',
    a: 'A monolith is one deployable — simple to build, test, and deploy, but scales and evolves as a unit. Microservices split by business capability so teams deploy and scale independently — at the cost of network calls, distributed data, and operational complexity. Start with a modular monolith; extract services only when you need independent scaling/teams.' },
  { category: 'Microservices', level: 'Mid', q: 'Sync vs async communication between services?',
    a: 'Synchronous (REST/gRPC) is simple and immediate but couples services and cascades failures. Asynchronous (message queue/events) decouples them and absorbs load, at the cost of eventual consistency and harder debugging. Use sync for request/response, async for workflows and fan-out.' },
  { category: 'Microservices', level: 'Senior', q: 'How do you handle transactions across services (the Saga pattern)?',
    a: 'You can\'t use one ACID transaction across services. A Saga is a sequence of local transactions; if a step fails, you run compensating actions to undo the completed ones. Orchestration (a coordinator drives it) or choreography (services react to events). Pair with idempotency and the outbox pattern for reliability.' },
  { category: 'Microservices', level: 'Senior', q: 'What is the outbox pattern and why use it?',
    a: 'It solves "dual write": you must update your DB and publish an event atomically. Write the event to an outbox table in the SAME transaction as the state change; a separate publisher reads the outbox and sends events (at-least-once). This guarantees you never save data but lose the event. Consumers must be idempotent.' },
  { category: 'Microservices', level: 'Mid', q: 'What does an API Gateway do?',
    a: 'A single entry point that routes requests to the right service and handles cross-cutting concerns — auth, rate limiting, TLS, request aggregation, and versioning — so each service doesn\'t reimplement them and clients have one endpoint.' },
  { category: 'Microservices', level: 'Senior', q: 'How do services find each other (service discovery)?',
    a: 'Services register their instances in a registry (Consul, Eureka, or Kubernetes\' built-in DNS/Service). Clients (or a load balancer) query it to get healthy instances and balance across them. Health checks remove dead instances automatically.' },

  // ---------------- Testing ----------------
  { category: 'Testing', level: 'Junior', q: 'What is the AAA pattern?',
    a: 'Arrange–Act–Assert: set up the inputs and dependencies, call the method under test once, then assert on the outcome. It keeps tests readable and focused on a single behavior.' },
  { category: 'Testing', level: 'Junior', q: 'Unit vs integration vs end-to-end test?',
    a: 'Unit tests one small piece in isolation (fast, mocked deps). Integration tests components together (DB, HTTP). End-to-end tests the whole flow like a user. The test pyramid: many unit, fewer integration, fewest E2E.' },
  { category: 'Testing', level: 'Mid', q: 'Mock vs stub vs fake vs spy?',
    a: 'A stub returns canned data. A fake is a lightweight working implementation (in-memory repo). A spy records how it was called so you can assert on interactions. A mock is a pre-programmed spy with expectations. Collectively: "test doubles".' },
  { category: 'Testing', level: 'Mid', q: 'How do you make code testable?',
    a: 'Keep logic deterministic and pure where possible; inject dependencies (clock, DB, HTTP) via interfaces so tests can pass fakes; avoid statics/`DateTime.Now`/`new` of collaborators inside methods; separate decisions from side effects.' },
  { category: 'Testing', level: 'Senior', q: 'What is TDD, and what are its benefits?',
    a: 'Test-Driven Development: write a failing test, make it pass with minimal code, then refactor (red-green-refactor). Benefits: forces small testable design, gives a safety net for refactoring, and documents intent. Trade-off: discipline and slower initial pace.' },

  // ---------------- Clean Code ----------------
  { category: 'Clean Code', level: 'Junior', q: 'What makes code "clean"?',
    a: 'It reads clearly: intention-revealing names, small functions that do one thing, minimal nesting, no duplication (DRY), and few surprises. Clean code optimizes for the reader, because code is read far more than it\'s written.' },
  { category: 'Clean Code', level: 'Junior', q: 'What is a guard clause?',
    a: 'An early return that handles an edge/invalid case up front, so the main logic stays flat instead of nested inside ifs. It reduces indentation and cognitive load.' },
  { category: 'Clean Code', level: 'Mid', q: 'DRY vs WET — and can DRY go too far?',
    a: 'DRY = Don\'t Repeat Yourself; extract shared logic to one place. But premature or wrong abstraction couples unrelated things — "duplication is cheaper than the wrong abstraction". Deduplicate real, stable knowledge; tolerate incidental similarity.' },
  { category: 'Clean Code', level: 'Mid', q: 'What is a code smell? Give examples.',
    a: 'A surface symptom hinting at deeper trouble: long methods, large classes, long parameter lists, duplicated code, magic numbers, deep nesting, feature envy, and primitive obsession. Smells guide refactoring, they aren\'t bugs themselves.' },
  { category: 'Clean Code', level: 'Senior', q: 'How do you keep functions clean?',
    a: 'One responsibility, few arguments (bundle related ones into an object), no side effects hidden behind an innocent name, meaningful names over comments, and guard clauses over nesting. Extract until each function reads as a short paragraph.' },

  // ---------------- System Design (open-ended prompts) ----------------
  { category: 'System Design', level: 'Senior', q: 'How would you approach ANY system-design question?',
    a: 'A repeatable framework: (1) Clarify requirements & scale (users, QPS, read/write ratio, data size). (2) Define the API. (3) Design the data model. (4) Sketch the high-level architecture (clients → LB → services → storage/cache). (5) Deep-dive the bottleneck. (6) Discuss trade-offs (consistency vs availability, cost). Always state assumptions and drive the conversation.' },
  { category: 'System Design', level: 'Senior', q: 'Design a URL shortener (TinyURL).',
    a: 'API: POST /shorten → short code; GET /{code} → 301 redirect. Data: map code → long URL in a KV store. Codes: base62 of an auto-increment id, or a hash (handle collisions). Scale: reads ≫ writes, so cache hot codes (Redis) and use a CDN; shard the store by code. Extras: custom aliases, expiry, click analytics (async via a queue).' },
  { category: 'System Design', level: 'Senior', q: 'Design a rate limiter.',
    a: 'Algorithm: token bucket (allows bursts) or sliding-window counter (smoother). Store counters in Redis keyed by user/IP with TTLs; use atomic INCR/Lua so concurrent requests are safe. Deploy at the API gateway. Distributed: either centralize in Redis or approximate per-node. Return 429 with a Retry-After header.' },
  { category: 'System Design', level: 'Senior', q: 'Design a news feed / timeline (Twitter).',
    a: 'Two models: fan-out-on-write (push each post into followers\' feeds — fast reads, expensive for celebrities) vs fan-out-on-read (build the feed at read time — cheap writes, slow reads). Hybrid: push for normal users, pull for celebrities. Store feeds in a cache; paginate; rank by recency/relevance. Use a queue for the fan-out work.' },
  { category: 'System Design', level: 'Senior', q: 'Design a chat / messaging system (WhatsApp).',
    a: 'Persistent connections via WebSocket to gateway servers; a presence service tracks who\'s online. Messages go through a queue; store in a per-conversation table (partitioned by conversation id) for history. Delivery/read receipts as events. For offline users, store-and-forward + push notifications. Scale gateways horizontally with a session registry.' },
  { category: 'System Design', level: 'Senior', q: 'Design a notification system.',
    a: 'Producers publish events to a queue; a notification service fans out to channels (push, email, SMS) via provider adapters. Add user preferences, templating, deduplication/idempotency keys, retries with backoff + dead-letter queue, and rate limiting per user. Make it async and horizontally scalable; track delivery status.' },
  { category: 'System Design', level: 'Senior', q: 'Design a scalable key-value store.',
    a: 'Partition data across nodes with consistent hashing; replicate each key to N nodes for durability. Choose consistency (quorum reads/writes R+W>N for strong-ish, or eventual for availability — CAP). Handle failures with hinted handoff / read-repair. Add an in-memory cache and an LSM-tree storage engine for write-heavy loads.' },
  { category: 'System Design', level: 'Mid', q: 'Design typeahead / autocomplete.',
    a: 'Precompute a trie (or prefix table) of popular queries with weights; return top-K completions per prefix. Cache hot prefixes; update counts asynchronously from search logs. Serve from memory for low latency; debounce client requests. Shard the trie by prefix if it\'s huge.' },
  { category: 'System Design', level: 'Senior', q: 'Design a web crawler.',
    a: 'A frontier queue of URLs → fetchers → parsers that extract links → dedupe (seen-set / Bloom filter) → back to the frontier. Respect robots.txt and politeness (per-domain rate limits). Store pages in blob storage + a metadata index. Scale with many workers; prioritize by importance; handle traps and re-crawl scheduling.' },

  // ---------------- Design & Practices ----------------
  { category: 'Design & Practices', level: 'Mid', q: 'What are the SOLID principles?',
    a: 'Single Responsibility (one reason to change), Open/Closed (extend without modifying), Liskov Substitution (subtypes are safe substitutes), Interface Segregation (small focused interfaces), Dependency Inversion (depend on abstractions).' },
  { category: 'Design & Practices', level: 'Junior', q: 'Unit test vs integration test?',
    a: 'A unit test checks one small piece in isolation (fast, mocked dependencies). An integration test checks components together (DB, HTTP) — slower but catches wiring bugs. The test pyramid: many unit, fewer integration tests.' },
  { category: 'Design & Practices', level: 'Junior', q: 'Why depend on interfaces (dependency injection)?',
    a: 'So a class doesn\'t hard-wire its collaborators: it receives abstractions via its constructor. This makes code testable (inject fakes), swappable, and loosely coupled — the backbone of ASP.NET Core.' },
]
